# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.

image: docker:19-dind
services:
  - docker:19-dind

variables:
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""
  GIT_STRATEGY: clone
  DOCKER_DRIVER: overlay2

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
stages:
  - auc
  - deploy

build:
  stage: auc
  tags:
    - auc
  before_script:
    - mkdir -p ~/.docker
    - echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    - whoami
    - sudo echo "127.0.0.1 docker" > /etc/hosts

  script:
    - echo -n $DOCKERHUB_PASSWORD | docker login docker.io --username $DOCKERHUB_LOGIN --password-stdin
    - docker build -t 5575123963/auc:latest -f Dockerfile .
    - docker push 5575123963/auc:latest


deploy:
  tags:
    - deploy
  stage: deploy
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "=================deploy to host================="
    - |
      ssh -o StrictHostKeyChecking=no -t -t root@62.109.30.145 << EOF
      cd ../auc_backend
      ls
      docker-compose down
      docker rmi -f $(docker images -aq)
      docker-compose up -d --force-recreate
      exit 
      EOF

  only:
    - develop

