image: docker:20.10.24  # Используем официальный образ Docker с поддержкой buildx

variables:
  DOCKER_BUILDKIT: 1

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - gitlab-org-docker
  before_script:
    - mkdir -p ~/.docker
    - echo "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login docker.io --username "$DOCKERHUB_LOGIN" --password-stdin
    - docker buildx create --use  # Активируем buildx
    - docker buildx build --platform linux/amd64 -t 5575123963/auc:latest -f Dockerfile --push .

deploy:
  stage: deploy
  image: alpine:3.16
  tags:
    - gitlab-org-docker
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_DEV" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - |
      ssh -o StrictHostKeyChecking=no root@185.43.4.23 << 'EOF'
      cd ../lootor
      docker pull 5575123963/auc:latest
      docker-compose -f docker-compose.backend.yml down
      docker network rm lootor_network || true
      docker network create lootor_network || true
      docker-compose -f docker-compose.backend.yml up -d
      docker-compose -f docker-compose.backend.yml ps
      EOF
  only:
    - dev