run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gocyclo
    - gofmt
    - revive
    - errcheck

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - internal/infrastructure    # пропускать всю папку
  exclude-files:
    - ".*\\.pb\\.go"             # пропускать все .pb.go файлы
    - ".*\\.proto"               # пропускать все .proto файлы
