run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gocyclo
    - gofmt
    - revive
    - errcheck

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
