version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  backend:
    image: 5575123963/auc:latest
    env_file:
      - .env
    ports:
      - "5111:5111"
  auc:
    image: postgres:latest
    environment:
      POSTGRES_USER: auc
      POSTGRES_DB: lootor
      POSTGRES_PASSWORD: aucer
    volumes:
      - data:/var/lib/postgresql/da
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:8.17.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.17.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
volumes:
  data:
  elasticsearch_data: