version: "3"
services:
  backend:
    image: 5575123963/auc:latest
    env_file:
      - .env
    ports:
      - "5111:5111"
  auc:
    image: postgres:latest
    environment:
      POSTGRES_USER: auc
      POSTGRES_DB: lootor
      POSTGRES_PASSWORD: aucer
    volumes:
      - data:/var/lib/postgresql/da
    ports:
      - "5432:5432"
volumes:
  data: