services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - lootor_network
  backend:
    image: 5575123963/auc:latest
    env_file:
      - .env.backend
    ports:
      - "5111:5111"
    networks:
      - lootor_network
  auc:
    image: postgres:latest
    environment:
      POSTGRES_USER: auc
      POSTGRES_DB: lootor
      POSTGRES_PASSWORD: aucer
    volumes:
      - data:/var/lib/postgresql/da
    ports:
      - "5432:5432"
    networks:
      - lootor_network

  elasticsearch:
    image: elasticsearch:8.17.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - lootor_network

  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --appendonly yes          
      --maxmemory 2gb               
      --maxmemory-policy allkeys-lru 
      --save 300 10
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lootor_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
    driver: local
  data:
  elasticsearch_data:
networks:
  lootor_network:
    driver: bridge