basePath: /
host: dev.lootor.me
info:
  contact: {}
  description: Дока для ауса
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Lootor
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
