syntax = "proto3";

import "google/protobuf/struct.proto";

package posts;

option go_package = "./gen/go/microservices";

service PostsService {
  rpc CreatePost(CreatePostRequest) returns (PostResponse);

  rpc GetAllPosts(GetAllPostsRequest) returns (GetAllPostsResponse);

  rpc GetPostsByUser(GetPostsByUserRequest) returns (GetAllPostsResponse);

  rpc DeletePost(DeletePostRequest) returns (DeletePostResponse);

  rpc GetPost(PostRequest) returns (PostResponse);

  rpc IncrementReaction(ReactRequest) returns (ReactResponse);

  rpc DecrementReaction(ReactDecrementRequest) returns (ReactResponse);

  rpc UpdatePost(UpdatePostRequest) returns (PostResponse);

  rpc IncrementViews(ViewsRequest) returns (ViewsResponse);

  rpc IncrementCommentsCount(CommentsCountRequest) returns (CommentsCountResponse);

  rpc DecrementCommentsCount(CommentsCountRequest) returns (CommentsCountResponse);

  rpc GetCountByUser(CountRequest) returns (CountResponse);

  rpc GetPostByTranslit(PostRequestByTranslit) returns (PostResponse);

  rpc GetPostsByIds(GetPostsByIdsMapRequest) returns (GetPostsByIdsMapResponse);

  rpc GetPostsCountByUserLogin(GetPostsCountByUserLoginRequest) returns (GetPostsCountByUserLoginResponse);

  rpc GetReactionsCountByUserLogin(GetReactionsCountByUserLoginRequest) returns (GetReactionsCountByUserLoginResponse);

  rpc GetPostsCountsByUserLogins(GetPostsCountsByUserLoginsRequest) returns (GetPostsCountsByUserLoginsResponse);

}

message GetPostsCountsByUserLoginsRequest {
  repeated string user_logins = 1;
}

message GetPostsCountsByUserLoginsResponse {
  map<string, int64> data = 1;
}

message GetPostsCountByUserLoginRequest {
  string user_login = 1;
}

message GetPostsCountByUserLoginResponse {
  int64 count = 1;
}

message GetReactionsCountByUserLoginRequest {
  string user_login = 1;
}

message GetReactionsCountByUserLoginResponse {
  int64 count = 1;
}

message GetPostsByIdsMapRequest {
  repeated string post_ids = 1;
  string auth_user_login = 2;
  bool is_premium = 3;
}

message GetPostsByIdsMapResponse {
  map<string, PostItem> data = 1;
}

message CountRequest {
  string user_login = 1;
}

message CountResponse {
  int64 count = 1;
}

message ReactRequest {
  string reaction = 1;
  string user_login = 2;
  string post_id = 3;
}

message CommentsCountRequest {
  string post_id = 1;
}

message CommentsCountResponse {
  bool success = 1;
}

message ViewsRequest {
  repeated string post_ids = 1;
}

message ViewsResponse {
  bool success = 1;
}

message ReactDecrementRequest {
  string reaction = 1;
  string user_login = 2;
  string post_id = 3;
}

message ReactResponse {
  bool success = 1;
  string user_login = 2;
}

message CreatePostRequest {
  string date = 1;
  google.protobuf.Struct content = 2;
  string author = 3;
  bool is_draft = 4;
  string title = 5;
}

message UpdatePostRequest {
  string id = 1;
  google.protobuf.Struct content = 2;
  bool is_draft = 3;
  string title = 4;
  string translit = 5;
}

message DeletePostRequest {
  string id = 1;
}

message DeletePostResponse {
  bool success = 1;
  int64 react_count = 2;
  string title = 3;
}

message PostRequest {
  string id = 1;
  bool is_premium = 2;
  string auth_user_login = 3;
}

message PostRequestByTranslit {
  string translit = 1;
  bool is_premium = 2;
  string auth_user_login = 3;
}

message PostResponse {
  PostItem data = 1;
}

message GetAllPostsRequest {
  string offset = 2;
  string limit = 3;
  bool is_premium = 4;
  string order = 5;
  string auth_user_login = 6;
}

message GetPostsByUserRequest {
  string login = 1;
  string offset = 2;
  string limit = 3;
  bool is_premium = 4;
  string auth_user_login = 5;
  bool is_draft = 6;
}

message GetAllPostsResponse {
  repeated PostItem data = 1;
  string total = 2;
}

message React {
  string user_login = 1;
  string post_id = 2;
  string id = 3;
  string created_at = 4;
  string reaction = 5;
}

message PostItem {
  string id = 1;
  string date = 2;
  google.protobuf.Struct content = 3;
  string created_at = 4;
  string updated_at = 5;
  string deleted_at = 6;
  int64 heart_count = 7;
  int64 fire_count = 8;
  int64 glasses_count = 9;
  int64 laugh_count = 10;
  int64 tears_count = 11;
  int64 poker_face_count = 12;
  int64 eyes_count = 13;
  int64 angry_count = 14;
  int64 shit_count = 15;
  int64 clown_count = 16;
  int64 total_reactions = 17;
  string author = 18;
  repeated React reactions = 19;
  string reacted = 20;
  bool is_draft = 21;
  int64 views = 22;
  int64 comments_count = 23;
  string title = 24;
  string translit = 25;
  uint64 number_id = 26;
}
