// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/public/auth/reset": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "сброс пароля",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/public/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Авторизация",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SignInResponse"
                        }
                    }
                }
            }
        },
        "/public/auth/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "создание пользователя",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpResponse"
                        }
                    }
                }
            }
        },
        "/public/collection_item": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection items"
                ],
                "summary": "получение одного КИ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CollectionItemsDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/public/collection_item/entity": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection items"
                ],
                "summary": "получить КИ по кнтити",
                "parameters": [
                    {
                        "type": "string",
                        "description": "entity",
                        "name": "entity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AllCollectionsDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/public/collection_item/entity/type": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection items"
                ],
                "summary": "получить КИ по entity и типу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "entity",
                        "name": "entity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "поле сортировки% может быть  name, purchaseDate, purchasePrice, platform, type, rating",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "порядок сортировки asc или desc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "поиск среди коллекций по entity",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AllCollectionsDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/public/collections": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "получение коллекций по id или по логину + транслит",
                "parameters": [
                    {
                        "type": "string",
                        "description": "логин",
                        "name": "userLogin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "translit",
                        "name": "transliteration",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "поле сортировки% может быть  name, purchaseDate, purchasePrice, platform, type, rating",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "порядок сортировки asc или desc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "поиск по именам КИ внутри коллекции",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CollectionDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/public/collections/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "получение коллекций по логину",
                "parameters": [
                    {
                        "type": "string",
                        "description": "логин",
                        "name": "userLogin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "поле сортировки% может быть totalPrice, name, created, collectionItemsCount",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "порядок сортировки asc или desc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "поиск по именам коллекций",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AllCollectionsDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/public/collections/subscribe": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "подписка на коллекцию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "flag",
                        "name": "isSubscribe",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/public/events/filter": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "получить эвенты filtered",
                "parameters": [
                    {
                        "type": "string",
                        "description": "login",
                        "name": "userLogin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "collection id",
                        "name": "collectionId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "collection item id",
                        "name": "collectionItemId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "wish list item id",
                        "name": "wishListItemId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.EventsDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/public/images/{key}": {
            "get": {
                "produces": [
                    "image/png",
                    "image/jpeg",
                    "image/webp"
                ],
                "tags": [
                    "images"
                ],
                "summary": "получить изображение",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "image",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/public/search": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Поиск по коллекциям, ентити, КИ, тегам, юзерам",
                "parameters": [
                    {
                        "type": "string",
                        "description": "поисковая строка",
                        "name": "search",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/elasticsearch.SearchResult"
                        }
                    }
                }
            }
        },
        "/public/user": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "получение юзера по логину",
                "parameters": [
                    {
                        "type": "string",
                        "description": "логин",
                        "name": "login",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.DataUserResponseSwagger"
                        }
                    }
                }
            }
        },
        "/public/user/reset": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "смена пароля по токену",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChangePasswordReset"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/secured/collection_item": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection items"
                ],
                "summary": "Создание КИ",
                "parameters": [
                    {
                        "description": "поля создания",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CollectionItemsRequestCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CollectionItemsDataResponseSwagger"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection items"
                ],
                "summary": "удаление КИ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/secured/collection_item/copy": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection items"
                ],
                "summary": "копирование/перемещение КИ",
                "parameters": [
                    {
                        "description": "polya",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CollectionItemsCopyOrMoveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/secured/collection_item/like": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection items"
                ],
                "summary": "like/dislike",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/secured/collection_item/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection items"
                ],
                "summary": "обновление КИ",
                "parameters": [
                    {
                        "description": "поля создания",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CollectionItemsRequestCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CollectionItemsDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/secured/collections": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "Создание коллекции",
                "parameters": [
                    {
                        "description": "поля создания",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CollectionCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CollectionDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/secured/collections/like": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "like/dislike",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/secured/collections/tag": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "получить коллекции по тегу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tag",
                        "name": "tag",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "поле сортировки% может быть totalPrice, name, created, collectionItemsCount",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "порядок сортировки asc или desc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "поиск среди коллекций по тегу",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AllCollectionsDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/secured/collections/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "обновление коллекции",
                "parameters": [
                    {
                        "description": "поля создания",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CollectionCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CollectionDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/secured/entities": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entities"
                ],
                "summary": "поиск по entities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "имя",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.EntitiesDataResponseSwagger"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entities"
                ],
                "summary": "Создание entity",
                "parameters": [
                    {
                        "description": "поля создания",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EntitiesCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.EntitiesDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/secured/events": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "получить эвенты по юзеру из токена",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.EventsDataResponseSwagger"
                        }
                    }
                }
            }
        },
        "/secured/feedback": {
            "post": {
                "description": "Загрузка файла через multipart/form-data",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feedback"
                ],
                "summary": "Создать обращение",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файл для загрузки",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Заголовок тикета",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Описание тикета",
                        "name": "description",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/secured/images/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "удалить изображения из хранилища",
                "parameters": [
                    {
                        "description": "поля",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/s3.DeleteFilesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/s3.DeleteFilesResponse"
                        }
                    }
                }
            }
        },
        "/secured/images/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Загрузить изображения в хранилище",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "csv",
                        "description": "файлы для загрузки",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ширина картинки",
                        "name": "width",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "высота",
                        "name": "height",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ImagesResponse"
                        }
                    }
                }
            }
        },
        "/secured/item_types": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "itemTypes"
                ],
                "summary": "получить список типов КИ",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ItemTypesDataResponse"
                        }
                    }
                }
            }
        },
        "/secured/platforms": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "platforms"
                ],
                "summary": "получить список платформ",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.PlatformsDataResponse"
                        }
                    }
                }
            }
        },
        "/secured/tags": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Поиск по тегам",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.TagsSwagger"
                        }
                    }
                }
            }
        },
        "/secured/user/password": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Смена пароля",
                "parameters": [
                    {
                        "description": "isLike",
                        "name": "isLike",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    {
                        "type": "string",
                        "description": "User data",
                        "name": "login",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/secured/user/rating": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Лайк/дизлайк",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LikeUserSwagger"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/secured/user/subscriptions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Подписка одного юзера на другого",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "признак подписки",
                        "name": "isSubscribe",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User data",
                        "name": "login",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        },
        "/secured/user/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "смена некоторых данных пользователя",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRequestUpdate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.DataUserResponseSwagger"
                        }
                    }
                }
            }
        },
        "/secured/wishlist": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wishlist"
                ],
                "summary": "получить вишлист по юзер логину",
                "parameters": [
                    {
                        "type": "string",
                        "description": "login",
                        "name": "userLogin",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.WishlistDataResponseSwagger"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wishlist"
                ],
                "summary": "Создание экземпляра вишлиста",
                "parameters": [
                    {
                        "description": "поля создания",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WishListCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CommonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AllCollectionsDataResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CollectionsResponseSwagger"
                    }
                }
            }
        },
        "dto.CollectionDataResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CollectionsResponseSwagger"
                }
            }
        },
        "dto.CollectionItemsDataResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CollectionItemsResponseSwagger"
                }
            }
        },
        "dto.CollectionItemsResponseSwagger": {
            "type": "object",
            "properties": {
                "collection": {
                    "type": "string"
                },
                "copyNumber": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "edition": {
                    "type": "string"
                },
                "entities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EntitiesSwagger"
                    }
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "isOwner": {
                    "type": "boolean"
                },
                "itemType": {
                    "$ref": "#/definitions/models.ItemTypes"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/dto.UsersSwagger"
                },
                "platform": {
                    "$ref": "#/definitions/models.Platforms"
                },
                "purchaseDate": {
                    "type": "string"
                },
                "purchasePrice": {
                    "type": "number"
                },
                "rating": {
                    "type": "number"
                },
                "sealed": {
                    "type": "boolean"
                },
                "shippingCost": {
                    "type": "number"
                }
            }
        },
        "dto.CollectionItemsSwagger": {
            "type": "object",
            "properties": {
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CollectionsSwagger"
                    }
                },
                "copyNumber": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "edition": {
                    "type": "string"
                },
                "entities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EntitiesSwagger"
                    }
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "itemType": {
                    "$ref": "#/definitions/models.ItemTypes"
                },
                "itemTypeID": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/dto.UsersSwagger"
                },
                "platform": {
                    "$ref": "#/definitions/models.Platforms"
                },
                "platformID": {
                    "type": "string"
                },
                "purchaseDate": {
                    "type": "string"
                },
                "purchasePrice": {
                    "type": "number"
                },
                "rating": {
                    "type": "number"
                },
                "sealed": {
                    "type": "boolean"
                },
                "shippingCost": {
                    "type": "number"
                },
                "transliteration": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userLogin": {
                    "type": "string"
                }
            }
        },
        "dto.CollectionsResponseSwagger": {
            "type": "object",
            "properties": {
                "bannerUrl": {
                    "type": "string"
                },
                "canLike": {
                    "type": "boolean"
                },
                "canSubscribe": {
                    "type": "boolean"
                },
                "collectionItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CollectionItemsResponseSwagger"
                    }
                },
                "collectionItemsCount": {
                    "type": "integer"
                },
                "created": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isOwner": {
                    "type": "boolean"
                },
                "isPrivate": {
                    "type": "boolean"
                },
                "likesCount": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "shareString": {
                    "type": "string"
                },
                "shippingTotal": {
                    "type": "number"
                },
                "subscribersCount": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TagsSwagger"
                    }
                },
                "totalPrice": {
                    "type": "number"
                },
                "transliteration": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserResponseSwagger"
                }
            }
        },
        "dto.CollectionsSwagger": {
            "type": "object",
            "properties": {
                "bannerUrl": {
                    "type": "string"
                },
                "collectionItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CollectionItemsSwagger"
                    }
                },
                "created": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isPrivate": {
                    "type": "boolean"
                },
                "likes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "shareString": {
                    "type": "string"
                },
                "shippingTotal": {
                    "type": "integer"
                },
                "subscribersCount": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TagsSwagger"
                    }
                },
                "totalPrice": {
                    "type": "integer"
                },
                "transliteration": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UsersSwagger"
                },
                "userLogin": {
                    "type": "string"
                }
            }
        },
        "dto.CommonResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Resp"
                }
            }
        },
        "dto.DataUserResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UserResponseSwagger"
                }
            }
        },
        "dto.EntitiesDataResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EntitiesSwagger"
                    }
                }
            }
        },
        "dto.EntitiesSwagger": {
            "type": "object",
            "properties": {
                "collectionItem": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CollectionItemsSwagger"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.EventsDataResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EventsSwagger"
                    }
                }
            }
        },
        "dto.EventsSwagger": {
            "type": "object",
            "properties": {
                "Id": {
                    "type": "string"
                },
                "action": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "eventTargetType": {
                    "description": "\"collection\", \"user\" или \"item\"",
                    "type": "string"
                },
                "initiator": {
                    "$ref": "#/definitions/dto.UsersSwagger"
                },
                "initiatorLogin": {
                    "type": "string"
                },
                "targetCollection": {
                    "$ref": "#/definitions/dto.CollectionsSwagger"
                },
                "targetCollectionID": {
                    "type": "string"
                },
                "targetItem": {
                    "$ref": "#/definitions/dto.CollectionItemsSwagger"
                },
                "targetItemID": {
                    "type": "string"
                },
                "targetName": {
                    "type": "string"
                },
                "targetUser": {
                    "$ref": "#/definitions/dto.UsersSwagger"
                },
                "targetUserLogin": {
                    "type": "string"
                }
            }
        },
        "dto.ImagesResponse": {
            "type": "object",
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.LikeUserSwagger": {
            "type": "object",
            "properties": {
                "isLike": {
                    "type": "boolean"
                }
            }
        },
        "dto.Resp": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.TagsSwagger": {
            "type": "object",
            "properties": {
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CollectionsSwagger"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.UserResponseSwagger": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "backgroundUrl": {
                    "type": "string"
                },
                "canSubscribe": {
                    "type": "boolean"
                },
                "collectionItemsCount": {
                    "type": "integer",
                    "default": 0
                },
                "collectionSubscriptions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "collectionsCount": {
                    "type": "integer",
                    "default": 0
                },
                "created": {
                    "type": "string"
                },
                "dislikes": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "likes": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "subscribers": {
                    "type": "integer"
                },
                "subscriptions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "telegramId": {
                    "type": "string"
                },
                "totalSum": {
                    "type": "integer",
                    "default": 0
                },
                "userName": {
                    "type": "string"
                },
                "vkId": {
                    "type": "string"
                }
            }
        },
        "dto.UsersSwagger": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "backgroundUrl": {
                    "type": "string"
                },
                "collectionSubscriptions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created": {
                    "type": "string"
                },
                "dislikes": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "likes": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "subscribers": {
                    "type": "integer"
                },
                "subscriptions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "telegramId": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "verificationToken": {
                    "type": "string"
                },
                "vkId": {
                    "type": "string"
                }
            }
        },
        "dto.WishlistDataResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.WishlistDataResponseSwagger"
                    }
                }
            }
        },
        "elasticsearch.SearchResult": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "object",
                    "properties": {
                        "hits": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "_index": {
                                        "type": "string"
                                    },
                                    "_source": {
                                        "type": "object",
                                        "additionalProperties": true
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "models.ChangePasswordReset": {
            "type": "object",
            "required": [
                "password",
                "token"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.CollectionCreateRequest": {
            "type": "object",
            "properties": {
                "bannerUrl": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "isPrivate": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transliteration": {
                    "type": "string"
                },
                "userLogin": {
                    "type": "string"
                }
            }
        },
        "models.CollectionItemsCopyOrMoveRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "sourceCollectionId": {
                    "type": "string"
                },
                "targetCollectionIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.CollectionItemsRequestCreate": {
            "type": "object",
            "properties": {
                "collection": {
                    "type": "string"
                },
                "copyNumber": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "description": {
                    "type": "string"
                },
                "edition": {
                    "type": "string"
                },
                "entities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "itemType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "purchaseDate": {
                    "type": "string"
                },
                "purchasePrice": {
                    "type": "number"
                },
                "rating": {
                    "type": "number"
                },
                "sealed": {
                    "type": "boolean"
                },
                "shippingCost": {
                    "type": "number"
                }
            }
        },
        "models.EntitiesCreateRequest": {
            "type": "object",
            "properties": {
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ItemTypes": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ruName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.ItemTypesDataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ItemTypes"
                    }
                }
            }
        },
        "models.Platforms": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.PlatformsDataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Platforms"
                    }
                }
            }
        },
        "models.SignInRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.SignInResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "models.SignUpRequest": {
            "type": "object",
            "required": [
                "email",
                "login",
                "password",
                "userName"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "models.SignUpResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                }
            }
        },
        "models.UserRequestUpdate": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "backgroundUrl": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "models.WishListCreateRequest": {
            "type": "object",
            "properties": {
                "collectionItemId": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "purchaseLinks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "s3.DeleteFilesRequest": {
            "type": "object",
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "s3.DeleteFilesResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "notFound": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "dev.lootor.me",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "Lootor",
	Description:      "Документация к API Lootor.me",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
